// Generated by CoffeeScript 1.10.0
(function() {
  var CND, alert, badge, debug, echo, help, info, isa_folder, join, log, njs_fs, njs_path, rpr, urge, warn, whisper,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  njs_path = require('path');

  njs_fs = require('fs');

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'mkts/plugin-manager';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  join = njs_path.resolve;

  isa_folder = function(route) {
    return (njs_fs.statSync(route)).isDirectory();
  };

  this.find_plugin_package_infos = function(plugin_home, settings) {
    var R, error, error1, i, keyword, keywords, len, message, package_info, plugin_name, plugin_names, plugin_route, ref;
    keyword = (ref = settings != null ? settings['keyword'] : void 0) != null ? ref : 'mingkwai-typesetter-plugin';
    help("looking for " + keyword + " in " + plugin_home);
    plugin_names = njs_fs.readdirSync(plugin_home);
    R = {};
    for (i = 0, len = plugin_names.length; i < len; i++) {
      plugin_name = plugin_names[i];
      if (plugin_name.startsWith('.')) {
        continue;
      }
      plugin_route = join(plugin_home, plugin_name);
      if (!isa_folder(plugin_route)) {
        continue;
      }
      try {
        package_info = require(join(plugin_route, 'package.json'));
      } catch (error1) {
        error = error1;
        message = error.message;
        if (message.startsWith('Cannot find module ')) {
          warn(message + " (ok)");
          continue;
        }
        throw error;
      }
      if ((keywords = package_info['keywords']) != null) {
        if (indexOf.call(keywords, keyword) >= 0) {
          urge("found " + keyword + ": " + plugin_route);
          R[plugin_route] = package_info;
        }
      }
    }
    return R;
  };

  if (module.parent == null) {
    debug(this.find_plugin_package_infos(join(__dirname, 'node_modules')));
  }

}).call(this);

//# sourceMappingURL=plugin-manager.js.map
